services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
  ny_taxi_postgres_data:


  # docker run -it \
  #   --network=week_1_default \
  #   taxi_ingest:v001 \
  #       --user=root \
  #       --password=root \
  #       --host=pgdatabase \
  #       --port=5432 \
  #       --db=ny_taxi \
  #       --table_name=zones \
  #       --url=${URL}
